<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaymentMethodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paymentMethods = [
            // Bank Transfer Methods
            [
                'code' => 'bca_transfer',
                'name' => 'Transfer Bank BCA',
                'category' => 'bank_transfer',
                'description' => 'Transfer melalui Bank BCA',
                'bank_name' => 'Bank Central Asia (BCA)',
                'account_number' => '1234567890',
                'account_holder_name' => 'LSP Pustaka Ilmiah Elektronik',
                'provider_name' => null,
                'gateway_code' => null,
                'gateway_config' => null,
                'admin_fee_percentage' => 0,
                'admin_fee_fixed' => 0,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Transfer ke rekening BCA 1234567890 a.n LSP Pustaka Ilmiah Elektronik. Simpan bukti transfer dan upload pada form konfirmasi pembayaran.',
                'display_order' => 1,
                'is_active' => true,
                'requires_manual_verification' => true,
            ],
            [
                'code' => 'bni_transfer',
                'name' => 'Transfer Bank BNI',
                'category' => 'bank_transfer',
                'description' => 'Transfer melalui Bank BNI',
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'account_number' => '0987654321',
                'account_holder_name' => 'LSP Pustaka Ilmiah Elektronik',
                'provider_name' => null,
                'gateway_code' => null,
                'gateway_config' => null,
                'admin_fee_percentage' => 0,
                'admin_fee_fixed' => 0,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Transfer ke rekening BNI 0987654321 a.n LSP Pustaka Ilmiah Elektronik. Simpan bukti transfer dan upload pada form konfirmasi pembayaran.',
                'display_order' => 2,
                'is_active' => true,
                'requires_manual_verification' => true,
            ],
            [
                'code' => 'mandiri_transfer',
                'name' => 'Transfer Bank Mandiri',
                'category' => 'bank_transfer',
                'description' => 'Transfer melalui Bank Mandiri',
                'bank_name' => 'Bank Mandiri',
                'account_number' => '1122334455',
                'account_holder_name' => 'LSP Pustaka Ilmiah Elektronik',
                'provider_name' => null,
                'gateway_code' => null,
                'gateway_config' => null,
                'admin_fee_percentage' => 0,
                'admin_fee_fixed' => 0,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Transfer ke rekening Mandiri 1122334455 a.n LSP Pustaka Ilmiah Elektronik. Simpan bukti transfer dan upload pada form konfirmasi pembayaran.',
                'display_order' => 3,
                'is_active' => true,
                'requires_manual_verification' => true,
            ],

            // E-Wallet Methods
            [
                'code' => 'gopay',
                'name' => 'GoPay',
                'category' => 'e_wallet',
                'description' => 'Pembayaran menggunakan GoPay',
                'bank_name' => null,
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => 'GoPay',
                'gateway_code' => 'midtrans',
                'gateway_config' => json_encode([
                    'payment_type' => 'gopay',
                ]),
                'admin_fee_percentage' => 2,
                'admin_fee_fixed' => 0,
                'min_amount' => 10000,
                'max_amount' => 2000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Anda akan diarahkan ke aplikasi GoPay untuk menyelesaikan pembayaran.',
                'display_order' => 4,
                'is_active' => true,
                'requires_manual_verification' => false,
            ],
            [
                'code' => 'ovo',
                'name' => 'OVO',
                'category' => 'e_wallet',
                'description' => 'Pembayaran menggunakan OVO',
                'bank_name' => null,
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => 'OVO',
                'gateway_code' => 'midtrans',
                'gateway_config' => json_encode([
                    'payment_type' => 'ovo',
                ]),
                'admin_fee_percentage' => 2,
                'admin_fee_fixed' => 0,
                'min_amount' => 10000,
                'max_amount' => 2000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Anda akan diarahkan ke aplikasi OVO untuk menyelesaikan pembayaran.',
                'display_order' => 5,
                'is_active' => true,
                'requires_manual_verification' => false,
            ],
            [
                'code' => 'dana',
                'name' => 'DANA',
                'category' => 'e_wallet',
                'description' => 'Pembayaran menggunakan DANA',
                'bank_name' => null,
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => 'DANA',
                'gateway_code' => 'midtrans',
                'gateway_config' => json_encode([
                    'payment_type' => 'dana',
                ]),
                'admin_fee_percentage' => 2,
                'admin_fee_fixed' => 0,
                'min_amount' => 10000,
                'max_amount' => 2000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Anda akan diarahkan ke aplikasi DANA untuk menyelesaikan pembayaran.',
                'display_order' => 6,
                'is_active' => true,
                'requires_manual_verification' => false,
            ],

            // QRIS
            [
                'code' => 'qris',
                'name' => 'QRIS',
                'category' => 'qris',
                'description' => 'Pembayaran menggunakan QRIS (semua dompet digital)',
                'bank_name' => null,
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => 'QRIS',
                'gateway_code' => 'midtrans',
                'gateway_config' => json_encode([
                    'payment_type' => 'qris',
                ]),
                'admin_fee_percentage' => 0.7,
                'admin_fee_fixed' => 0,
                'min_amount' => 1000,
                'max_amount' => 10000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Scan QR Code yang ditampilkan menggunakan aplikasi pembayaran digital Anda.',
                'display_order' => 7,
                'is_active' => true,
                'requires_manual_verification' => false,
            ],

            // Virtual Account
            [
                'code' => 'va_bca',
                'name' => 'Virtual Account BCA',
                'category' => 'virtual_account',
                'description' => 'Pembayaran melalui Virtual Account BCA',
                'bank_name' => 'Bank Central Asia (BCA)',
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => 'BCA',
                'gateway_code' => 'midtrans',
                'gateway_config' => json_encode([
                    'payment_type' => 'bank_transfer',
                    'bank' => 'bca',
                ]),
                'admin_fee_percentage' => 0,
                'admin_fee_fixed' => 4000,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Nomor Virtual Account akan dikirimkan setelah Anda memilih metode pembayaran ini. Transfer sesuai nominal yang tertera.',
                'display_order' => 8,
                'is_active' => true,
                'requires_manual_verification' => false,
            ],
            [
                'code' => 'va_bni',
                'name' => 'Virtual Account BNI',
                'category' => 'virtual_account',
                'description' => 'Pembayaran melalui Virtual Account BNI',
                'bank_name' => 'Bank Negara Indonesia (BNI)',
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => 'BNI',
                'gateway_code' => 'midtrans',
                'gateway_config' => json_encode([
                    'payment_type' => 'bank_transfer',
                    'bank' => 'bni',
                ]),
                'admin_fee_percentage' => 0,
                'admin_fee_fixed' => 4000,
                'min_amount' => 10000,
                'max_amount' => 50000000,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Nomor Virtual Account akan dikirimkan setelah Anda memilih metode pembayaran ini. Transfer sesuai nominal yang tertera.',
                'display_order' => 9,
                'is_active' => true,
                'requires_manual_verification' => false,
            ],

            // Cash
            [
                'code' => 'cash',
                'name' => 'Tunai',
                'category' => 'cash',
                'description' => 'Pembayaran tunai di kantor LSP',
                'bank_name' => null,
                'account_number' => null,
                'account_holder_name' => null,
                'provider_name' => null,
                'gateway_code' => null,
                'gateway_config' => null,
                'admin_fee_percentage' => 0,
                'admin_fee_fixed' => 0,
                'min_amount' => 0,
                'max_amount' => null,
                'icon_path' => null,
                'logo_url' => null,
                'instructions' => 'Datang ke kantor LSP Pustaka Ilmiah Elektronik untuk melakukan pembayaran tunai. Pastikan membawa invoice/bukti pendaftaran.',
                'display_order' => 10,
                'is_active' => true,
                'requires_manual_verification' => true,
            ],
        ];

        foreach ($paymentMethods as $method) {
            DB::table('payment_methods')->insert(array_merge($method, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
